---
brew:
  - asio
  - assimp
  - bison
  - bullet
  - cmake
  - console_bridge
  - cppcheck
  - cunit
  - eigen
  - freetype
  - graphviz
  - opencv
  - openssl
  - orocos-kdl
  - pcre
  - poco
  - pyqt: 5
  - python: 3.11
  - qt: 5
  - sip
  - spdlog
  - tinyxml
  - tinyxml2

pip:
  - argcomplete
  - catkin_pkg
  - colcon-common-extensions
  - coverage
  - cryptography
  - empy: 3.3.4
  - flake8
  - flake8-blind-except: 0.1.1
  - flake8-builtins
  - flake8-class-newline
  - flake8-comprehensions
  - flake8-deprecated
  - flake8-docstrings
  - flake8-import-order
  - flake8-quotes
  - importlib-metadata
  - jsonschema
  - lark: 1.1.1
  - lxml
  - matplotlib
  - mock
  - mypy: 0.931
  - netifaces
  - nose
  - pep8
  - psutil
  - pydocstyle
  - pydot
  - pyparsing: 2.4.7
  - pytest-mock
  - rosdep
  - rosdistro
  - setuptools: 59.6.0
  - vcstool
