# ARCS Workspace Configuration
repositories:
  arcs_msgs:
    type: git
    url: git@github.com:csun-arcs/arcs_msgs.git
    version: main
  arcs_bringup:
    type: git
    url: git@github.com:csun-arcs/arcs_bringup.git
    version: main
  arcs_description:
    type: git
    url: git@github.com:csun-arcs/arcs_description.git
    version: main
  arcs_simulation:
    type: git
    url: git@github.com:csun-arcs/arcs_simulation.git
    version: main
  arcs_perception:
    type: git
    url: git@github.com:csun-arcs/arcs_perception.git
    version: main
  arcs_control:
    type: git
    url: git@github.com:csun-arcs/arcs_control.git
    version: main
  arcs_navigation:
    type: git
    url: git@github.com:csun-arcs/arcs_navigation.git
    version: main
