# CoHORT Workspace Configuration
repositories:
  #
  # TODO: The following package has not yet been implemented.
  #
  # arcs_cohort_msgs:
  #   type: git
  #   url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_msgs.git
  #   version: main
  arcs_cohort_description:
    type: git
    url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_description.git
    version: humble
  arcs_cohort_bringup:
    type: git
    url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_bringup.git
    version: main
  arcs_cohort_simulation:
    type: git
    url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_simulation.git
    version: humble
  #
  # TODO: The following packages have not yet been implemented.
  #
  # arcs_cohort_core:
  #   type: git
  #   url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_core.git
  #   version: main
  # arcs_cohort_sensing:
  #   type: git
  #   url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_sensing.git
  #   version: main
  arcs_cohort_control:
    type: git
    url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_control.git
    version: humble
  arcs_cohort_perception:
    type: git
    url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_perception.git
    version: main
  arcs_cohort_navigation:
    type: git
    url: ${ARCSCFG_CLONE_URL_PREFIX}csun-arcs/arcs_cohort_navigation.git
    version: humble
