name: Install ROS 2 Humble on Ubuntu Jammy
description: |
  This script installs ROS 2 Humble Hawksbill on Ubuntu 22.04 (Jammy Jellyfish)
os: ubuntu
ros_distro: humble
steps:
  - message: "Checking if ROS 2 Humble is already installed..."
    script: |
      #!/bin/bash
      if [ -f /opt/ros/humble/setup.bash ]; then
          echo "ROS 2 Humble is already installed. Skipping installation."
          exit 0
      fi

  - message: "Updating apt package index & setting locale..."
    script: |
      #!/bin/bash
      sudo apt-get update && sudo apt-get install locales
      sudo locale-gen en_US en_US.UTF-8
      sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
      export LANG=en_US.UTF-8

  - message: "Enabling Ubuntu Universe repository..."
    script: |
      #!/bin/bash
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository universe

  - message: "Adding ROS 2 GPG key..."
    script: |
      sudo apt-get update && sudo apt-get install curl -y
      sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

  - message: "Adding ROS 2 apt repository..."
    command: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

  - message: "Updating apt package index after adding ROS 2 repository..."
    command: "sudo apt-get update"

  - message: "Upgrading apt packages..."
    command: "sudo apt-get -y upgrade"

  - message: "Installing ROS 2 Humble desktop packages..."
    command: "sudo apt-get install -y ros-humble-desktop"

  - message: "Installing ROS 2 Humble developer tools..."
    command: "sudo apt-get install -y ros-dev-tools"

  - message: "Initializing rosdep..."
    script: |
      #!/bin/bash
      if ! rosdep version > /dev/null 2>&1; then
          sudo rosdep init
      fi
      rosdep update

  - message: "ROS 2 Humble installation complete. Please run 'arcscfg config' to configure your environment."
