name: Install ROS 2 Jazzy on macOS Sequoia
description: |
  This script installs ROS 2 Jazzy natively from source on macOS Sequoia.
os: macos
ros_distro: jazzy
steps:
  - message: "Updating Homebrew..."
    command: "brew update"
  - message: "Installing yq via Homebrew..."
    command: "brew install yq"
  - message: "Installing ROS 2 Homebrew dependencies..."
    command: |
      yq -r '.brew[] | (select(. | type == "!!map") | to_entries | map("\(.key)@\(.value)") | join(" ")) // (select(. | type == "!!str") | .)' ${ARCSCFG_ROOT}/arcscfg/config/dependencies/ros2_jazzy_macos_sequoia.yaml | xargs brew install
  - message: "Installation complete."
