name: Install ROS 2 Jazzy on macOS Sequoia
description: |
  This script installs ROS 2 Jazzy on macOS Sequoia.
os: macos
ros_distro: jazzy
steps:
  - message: "Updating Homebrew..."
    command: "echo brew update"
  - message: "Installing prerequisites..."
    commands:
      - "echo brew install python3"
      - "echo brew install cmake"
  - message: "Installing ROS 2 Jazzy..."
    script: |
      #!/bin/bash
      echo set -e
      # Add ROS 2 tap and install
      echo brew tap ros/dashing
      echo brew install ros-dashing-desktop
  - message: "Installation complete."
