name: Install ROS 2 Jazzy Jalisco from binaries on Ubuntu 24.04.1 (Noble Numbat)
description: |
  This script installs ROS 2 Jazzy Jalisco from binaries on Ubuntu 24.04.1 (Noble Numbat).
os: ubuntu
ros_distro: jazzy
steps:
  - message: "Checking if ROS 2 Jazzy is already installed..."
    script: |
      #!/bin/bash
      if [ -f /opt/ros/jazzy/setup.bash ]; then
          echo "ROS 2 Jazzy is already installed. Skipping installation."
          exit 0
      fi

  - message: "Updating apt package index..."
    command: "sudo apt-get update"

  - message: "Installing essential packages (curl, gnupg2, lsb-release)..."
    command: "sudo apt-get install -y curl gnupg2 lsb-release"

  - message: "Adding ROS 2 GPG key..."
    command: "sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc -o /usr/share/keyrings/ros-archive-keyring.gpg"

  - message: "Adding ROS 2 apt repository..."
    command: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null"

  - message: "Updating apt package index after adding ROS 2 repository..."
    command: "sudo apt-get update"

  - message: "Installing ROS 2 Jazzy desktop packages..."
    command: "sudo apt-get install -y ros-jazzy-desktop"

  - message: "Initializing rosdep..."
    script: |
      #!/bin/bash
      if ! rosdep version > /dev/null 2>&1; then
          sudo rosdep init
      fi
      rosdep update

  - message: "ROS 2 Jazzy installation complete. Please run 'arcscfg config' to configure your environment."
