name: Install ROS 2 Jazzy on Ubuntu Noble
description: |
  This script installs ROS 2 Jazzy on Ubuntu Noble 24.04
os: ubuntu
ros_distro: jazzy
steps:
  - message: "Checking if ROS 2 Jazzy is already installed..."
    script: |
      #!/bin/bash
      if [ -f /opt/ros/jazzy/setup.bash ]; then
          echo "ROS 2 Jazzy is already installed. Skipping installation."
          exit 0
      fi

  - message: "Setting locale..."
    script: |
      #!/bin/bash
      sudo apt-get update && sudo apt-get install -y locales
      sudo locale-gen en_US en_US.UTF-8
      sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
      export LANG=en_US.UTF-8

  - message: "Enabling Ubuntu Universe repository..."
    script: |
      #!/bin/bash
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository -y universe

  - message: "Adding ROS 2 GPG key with apt..."
    script: |
      #!/bin/bash
      sudo apt-get update && sudo apt-get install curl -y
      sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

  - message: "Adding ROS 2 apt repository to sources list..."
    command: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

  - message: "Installing development tools..."
    command: "sudo apt-get update && sudo apt-get install -y ros-dev-tools"

  - message: "Updating apt package index..."
    command: "sudo apt-get update"

  - message: "Upgrading packages.."
    command: "sudo apt-get upgrade -y"

  - message: "Installing ROS 2 Jazzy desktop packages..."
    command: "sudo apt-get install -y ros-jazzy-desktop"

  - message: "Initializing rosdep..."
    script: |
      #!/bin/bash
      if ! rosdep version > /dev/null 2>&1; then
          sudo rosdep init
      fi
      rosdep update

  - message: "ROS 2 Jazzy installation complete. Please run 'arcscfg config' to configure your environment."
